# Generated by Django 4.1.2 on 2022-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='apellido_materno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='apellido_paterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
